CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS belong;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CHANNEL;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    idu              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pseudo           VARCHAR(50)         NOT NULL,
    email            VARCHAR(255) UNIQUE NOT NULL,
    password         VARCHAR(255)        NOT NULL,
    avatar           TEXT,
    inscription_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHANNEL
(
    idc           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          VARCHAR(100) NOT NULL,
    description   TEXT,
    is_public     BOOLEAN   DEFAULT TRUE,
    url           VARCHAR(255),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idu           UUID  NOT NULL, -- Créateur/Admin du canal
    FOREIGN KEY (idu) REFERENCES USERS (idu)
);

CREATE TABLE MESSAGE
(
    idm       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content   TEXT        NOT NULL,
    send_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    edited    BOOLEAN   DEFAULT FALSE,
    edit_date TIMESTAMP,
    idu       UUID NOT NULL, -- Auteur
    idc       UUID NOT NULL, -- Canal
    ida       INTEGER,          -- Pièce jointe (opt)
    idm_2     INTEGER,          -- Réponse à un message (opt)
    FOREIGN KEY (idm_2) REFERENCES MESSAGE (idm),
    FOREIGN KEY (idc) REFERENCES CHANNEL (idc) ON DELETE CASCADE,
    FOREIGN KEY (idu) REFERENCES USERS (idu)
);

CREATE TABLE belong
(
    PRIMARY KEY (idu, idc),
    idu UUID NOT NULL,
    idc UUID NOT NULL,
    FOREIGN KEY (idc) REFERENCES CHANNEL (idc) ON DELETE CASCADE,
    FOREIGN KEY (idu) REFERENCES USERS (idu) ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO webuser;